Updating Sequencer plugin to accomodate linea_estimateGas fix
Consensys/linea-monorepo pull request #112
Opened 2024-09-27 14:56 UTC by Filter94

This PR implements issue(s) #

### Checklist

* [ ] I wrote new tests for my new core changes.
* [ ] I have successfully ran tests, style checker and build against my new changes locally.
* [ ] I have informed the team of any breaking changes if there are any.

2024-09-27 15:12 UTC, bradbown approved these changes

2024-09-27 15:18 UTC, diana-borbe-consensys approved these changes

2024-09-27 15:26 UTC, fab-10 requested changes
adjust the configuration to include
```
    Xin-process-rpc-enabled=true
    Xin-process-rpc-apis=["ETH"]
```

2024-09-27 15:37 UTC, jpnovais approved these changes

2024-09-27 16:27 UTC, fab-10 approved these changes

2024-10-02 15:58 UTC, fab-10 approved these changes

2024-10-02 17:01 UTC, naveen-consensys approved these changes

2024-10-02 20:38 UTC, merged

2024-10-02 21:49 UTC, jpnovais commented on docker/config/traces-node-v2/traces-node-v2-config.toml
> +plugin-linea-tracer-readiness-max-blocks-behind=5
What is flag for?

2024-10-03 05:53 UTC, Filter94 commented on docker/config/traces-node-v2/traces-node-v2-config.toml
> +plugin-linea-tracer-readiness-max-blocks-behind=5
All I found is description [here](https://github.com/Consensys/linea-tracer/blob/d9e42edeb1abd548fc848c9600b315fa36908fc6/arithmetization/src/main/java/net/consensys/linea/plugins/readiness/TracerReadinessCliOptions.java#L52)