fix: Correct errors in code and docs
Consensys/linea-monorepo pull request #378
Opened 2024-12-03 05:52 UTC by Anon-im

This PR implements issue(s) #

### Checklist

* [ ] I wrote new tests for my new core changes.
* [ ] I have successfully ran tests, style checker and build against my new changes locally.
* [ ] I have informed the team of any breaking changes if there are any.

2024-12-03 18:13 UTC, thedarkjester requested changes

2024-12-03 18:13 UTC, thedarkjester commented on contracts/contracts/test-contracts/LineaRollupV5.sol
>    /**
Something to note: this file is as deployed has been removed in V6 - this change

2024-12-03 18:13 UTC, thedarkjester commented on contracts/scripts/hardhat/postCompile.ts
> +const CONTRACT_OUTPUT_ABIS: { [contractName: string]: string } = {
line 21 was missed

2024-12-05 03:57 UTC, Anon-im commented
@thedarkjester Made all requested changes!

2024-12-06 19:34 UTC, Anon-im commented
Made all changes as required @thedarkjester

2024-12-22 07:09 UTC, Anon-im commented
@thedarkjester hello! I'va made all changes as required! Ready for review and merge!

2024-12-23 14:51 UTC, Anon-im reviewed
finished

2024-12-23 14:51 UTC, Anon-im commented on contracts/contracts/test-contracts/LineaRollupV5.sol
>    /**
Done

2024-12-23 14:51 UTC, Anon-im commented on contracts/scripts/hardhat/postCompile.ts
> +const CONTRACT_OUTPUT_ABIS: { [contractName: string]: string } = {
Done

2025-02-06 10:49 UTC, closed without merging

2025-02-06 10:49 UTC, thedarkjester commented
Thank you for your pull request and changes. 

Due to a change in our contribution guideline policy I am closing this pull request as it does not meet the contribution criteria.

Please see: https://github.com/Consensys/linea-monorepo?tab=readme-ov-file#guidelines-for-non-code-and-other-trivial-contributions